name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Get full Python version
      shell: bash
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
    - name: Build project for distribution
      shell: bash
      run: |
        python -m pip install -q build
        python -m build
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: steps.check-version.outputs.prerelease == 'true'